### ISSUE TITLE
403 Access denied after upgrading to 0.4.0 and bref 1.1.4

### ISSUE THREAD

**Issue by StephaneLeveugle** [brefphp/symfony-messenger#45]
Hi,

First of all I don't know if I should post this here or in https://github.com/brefphp/bref/.

I've been getting the error `HTTP 403 returned for "https://sqs.eu-west-3.amazonaws.com/".  Code:    AccessDenied Message: Access to the resource https://sqs.eu-west-3.amazonaws.com/ is denied. Type:    Sender Detail:   ` whenever I try to call one of my SQS queues.

I've been using `bref/symfony-messenger` 0.2.0 and `bref/bref` 0.5.29 without any issue but I now get the 403 error since I upgraded to `bref/symfony-messenger` 0.4.0 and `bref/bref` 1.1.4

I didn't change anything in AWS or in the credentials, and reverting to the previous version fixes the issue.
I only made the required changes so that the configuration works with the new version, like changing the runtime from `provided` to `provided.al2`

This is the content of my messenger.yaml:

```
framework:
  messenger:
    transports:
      export:
        dsn: '%env(MESSENGER_TRANSPORT_DSN_EXPORT)%'
        options:
          auto_setup: false
        retry_strategy:
          max_retries: 1
      import:
        dsn: '%env(MESSENGER_TRANSPORT_DSN_IMPORT)%'
        options:
          auto_setup: false
        retry_strategy:
          max_retries: 1
      analyze:
        dsn: '%env(MESSENGER_TRANSPORT_DSN_ANALYZE)%'
        options:
          auto_setup: false
        retry_strategy:
          max_retries: 1

    routing:
      'App\Message\ExportMessage': export
      'App\Message\ImportMessage': import
      'App\Message\AnalyzeInvoiceMessage': analyze

bref_messenger:
  sqs: true # Register the SQS transport
```
Do you know of anything I should be doing so that the authorization works with newer versions of `bref/symfony-messenger` and `bref/bref`?
I've been struggling with this for days so if you have any idea of what could be the issue here please let me know.

Thank you
