### ISSUE TITLE
Invoke error

### ISSUE THREAD

**Issue by JKetelaar** [brefphp/symfony-messenger#46]
With a setup using a function to use SNS, I am getting the following error:
```
{
    "errorType": "Symfony\\Component\\Messenger\\Exception\\MessageDecodingFailedException",
    "errorMessage": "Could not decode message using PHP serialization: {\"notificationType\":\"Bounce\",\"bounce\":{\"feedbackId\":\"01070177b7c56aa1-117088ce-e70c-42c6-9120-42aacdde7907-000000\",\"bounceType\":\"Permanent\",\"bounceSubType\":\"General\",\"bouncedRecipients\":[{\"emailAddress\":\"bounce@simulator.amazonses.com\",\"action\":\"failed\",\"status\":\"5.1.1\",\"diagnosticCode\":\"smtp; 550 5.1.1 user unknown\"}],\"timestamp\":\"2021-02-19T00:51:44.000Z\",\"remoteMtaIp\":\"3.226.40.239\",\"reportingMTA\":\"dsn; b224-13.smtp-out.eu-central-1.amazonses.com\"},\"mail\":{\"timestamp\":\"2021-02-19T00:51:42.822Z\",\"source\":\"jketelaar@intercube.io\",\"sourceArn\":\"arn:aws:ses:eu-central-1:544387708820:identity/jketelaar@intercube.io\",\"sourceIp\":\"178.132.211.234\",\"sendingAccountId\":\"544387708820\",\"messageId\":\"01070177b7c56466-279ebebc-6da2-4a1c-af23-b78eac23a6da-000000\",\"destination\":[\"bounce@simulator.amazonses.com\"]}}.",
    "stack": [
        "#0 /var/task/vendor/symfony/messenger/Transport/Serialization/PhpSerializer.php(38): Symfony\\Component\\Messenger\\Transport\\Serialization\\PhpSerializer->safelyUnserialize()",
        "#1 /var/task/vendor/bref/symfony-messenger/src/Service/Sns/SnsConsumer.php(40): Symfony\\Component\\Messenger\\Transport\\Serialization\\PhpSerializer->decode()",
        "#2 /var/task/vendor/bref/bref/src/Event/Sns/SnsHandler.php(18): Bref\\Symfony\\Messenger\\Service\\Sns\\SnsConsumer->handleSns()",
        "#3 /var/task/vendor/bref/bref/src/Runtime/Invoker.php(29): Bref\\Event\\Sns\\SnsHandler->handle()",
        "#4 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(102): Bref\\Runtime\\Invoker->invoke()",
        "#5 /opt/bref/bootstrap.php(43): Bref\\Runtime\\LambdaRuntime->processNextEvent()",
        "#6 {main}"
    ]
}
```

Any clue of what I'm doing wrong?

Here's some more information about the application:

`config/packages/messenger.yaml`:
```yml
framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            'App\Message\SesMessage': async
```

`src/Message/SesMessage.php`
```php
<?php
namespace App\Message;

class SesMessage
{
    private $content;

    public function __construct(string $content)
    {
        $this->content = $content;
    }

    public function getContent(): string
    {
        return $this->content;
    }
}
```

`src/MessageHandler/SesNotificationHandler.php`
```php
<?php

namespace App\MessageHandler;

use App\Message\SesMessage;
use Symfony\Component\Messenger\Handler\MessageHandlerInterface;

class SesNotificationHandler implements MessageHandlerInterface
{
    public function __invoke(SesMessage $message)
    {

    }
}
```

`bin/consumer.php`
```php
<?php declare(strict_types=1);

use App\Kernel;
use Bref\Symfony\Messenger\Service\Sns\SnsConsumer;
use Symfony\Component\Dotenv\Dotenv;

require dirname(__DIR__) . '/vendor/autoload.php';

(new Dotenv())->bootEnv(dirname(__DIR__) . '/.env');

$kernel = new Kernel($_SERVER['APP_ENV'], (bool)$_SERVER['APP_DEBUG']);
$kernel->boot();

// Return the Bref consumer service
return $kernel->getContainer()->get(SnsConsumer::class);
```

`serverless.yml`
```yml
...

functions:
  worker:
    handler: bin/consumer.php
    timeout: 20
    reservedConcurrency: 5 
    layers:
      - ${bref:layer.php-74}
    events:
      - sns:
          arn: arn:aws:sns:eu-central-1:1234567890:Test
```
